# Generated by Django 4.2.2 on 2023-06-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
    ]
